steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'container'
    - 'clusters'
    - 'get-credentials'
    - '${_CLUSTER_NAME}'
    - '--zone'
    - '${_CLUSTER_ZONE}'
    - '--project'
    - '${_PROJECT_ID}'
  id: 'Get GKE Credentials'
  
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/viks1102/gatekeeper-policy.git']
  dir: '/workspace'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - '/workspace/gatekeeper-policy/kubernetes-prod/constrainttemplate.yaml'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_CLUSTER_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - '/workspace/gatekeeper-policy/kubernetes-prod/constraint.yaml'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_CLUSTER_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _CLUSTER_NAME: 'gke-cluster-prod'
  _CLUSTER_ZONE: 'us-east1'
  _PROJECT_ID: 'dtonic-demo-k8s'